Flutter task 4
khlebobul/surf-flutter pull request #10
Opened 2024-02-14 22:19 UTC by khlebobul

2024-02-15 14:04 UTC, Evgenia-bit commented
В общем все хорошо. Если поправить комментарии, то будет вообще супер :fire:

Есть несколько недочетов по соответствию верстки дизайну, их можно тоже поправить по желанию:
- Не везде правильные отступы
- На шите сортировки отсутствует крестик
- Иконки в нижней навигационной панели не соответствуют дизайну кроме лупы (их можно было выгрузить из фигмы в .svg и добавить через бибилиотеку https://pub.dev/packages/flutter_svg/install)
- слева в шапке нет стрелочки 
- Текст в шапке не выровнен по центру
- Шит сортировки не должен быть на весь экран, обрати внимание на то, как сделано в фирме 
- Ширина кнопки в шите не совсем правильная
- Выделение выбранной сортировки не соответствует дизайну
- Цвет фона не соответствует дизайну

И по поводу оформления ПР:
- нужно следить, чтобы ничего лишнего не попадало в ПР, ненужные файлы можно добавлять в .gitignore
- лучше прикладывать видео или скриншоты работы, желательно продемонстрировать все возможные состояния приложения (например, наличие, отсутствие данных и загрузку)

2024-02-15 14:05 UTC, Evgenia-bit requested changes

2024-02-15 14:09 UTC, khlebobul commented
Большое спасибо за такой подробный фитбэк. Я в ближайшее время все поправлю и пришли на перепроверку.

2024-02-15 14:10 UTC, Evgenia-bit commented
И еще не увидела ответы на вопросы, нужно добавить их в  сущность ProductEntity, как написано в ТЗ

2024-02-15 16:20 UTC, khlebobul commented on flutter-task-4/lib/main.dart
> +        colorScheme: ColorScheme.fromSeed(
То есть в идеале файл main должен быть почти пустой?

2024-02-15 16:38 UTC, khlebobul commented on flutter-task-4/lib/widgets/products.dart
> +import 'package:surf_flutter_courses_template/widgets/filter.dart';
тогда получаю ошибку 

> Undefined name 'filterList'.
> Try correcting the name to one that is defined, or defining the name.

2024-02-16 06:48 UTC, Evgenia-bit commented on flutter-task-4/lib/main.dart
> +        colorScheme: ColorScheme.fromSeed(
да, так и есть

2024-02-16 06:58 UTC, Evgenia-bit commented on flutter-task-4/lib/widgets/products.dart
> +import 'package:surf_flutter_courses_template/widgets/filter.dart';
По сути импорт - это добавление возможности использовать в файле все классы, функции, переменные и прочее из другого файлы, который ты импортируешь. Бывает такое, что ты импортируешь несколько файлов, в которых есть допустим класс с одинаковым названием. И тогда, когда ты хочешь использовать этот класс, компилятор не понимает из какого именно файла он должен его брать. 
Вот тут и необходим префикс. Ты добавляешь его после импорта, тем самым задавая имя этому импорту и давая возможность обращаться к членам импортируемого файла через это имя.
В твоем случае ты случайно 2 раза импортировал 2 файл, на что компилятор стал ругаться и предложил добавить префикс. И к классу ты обращаешься через префикс filterList.FilterListScreen. Если ты удалишь импорт с префиксом и уберешь обращение к классу через префикс filterList, то ошибок не будет.

2024-02-19 06:03 UTC, Evgenia-bit commented
Здравствуйте! 

По поводу размера окна сортировки полагаю, что проблема только на андроиде.

Про Widget Inspector было немного сказано во введении. 
Вот есть гайд из официальной документации https://docs.flutter.dev/tools/devtools/inspector. 
Видео на русском - https://www.youtube.com/watch?v=VY13YP9Mukk.

2024-02-19 06:06 UTC, khlebobul commented
Спасибо

2024-02-19 06:06 UTC, merged