complete theme_changer task
khlebobul/surf-flutter pull request #23
Opened 2024-05-10 11:57 UTC by khlebobul

2024-05-13 15:15 UTC, danyaao requested changes
Почему у тебя почти все попало в data?
Мне кажется, цветам, к примеру, там точно не место. Они должны быть в своей папочке с темой, к примеру, uikit
Extension'ы контекста лучше вынести в util или что-то вроде того. По-хорошему там должен остаться один репозиторий
AppTheme в domain тоже странно выглядит, ее примерно туда же, куда и цвета

И ещё момент. Не лучше бы сделать, чтобы обновление темы было по выбору темы в модалке, а не по её закрытию?

2024-05-13 15:15 UTC, danyaao commented on intensive/flutter-task-6/lib/data/extensions/build_context_buttons_style_extension.dart
> +}
Круто, что используешь
В целом можно все расширения для context'а поместить в один файлик, а также в названия использовать не Extension, а просто X

2024-05-13 15:15 UTC, danyaao commented on intensive/flutter-task-6/lib/data/themes_repository/themes_repository.dart
> +    return Future.value();
Что-то не очень понятное)

Лучше все-таки основной метод сделать Future, и тут дожидаться результата через await

2024-05-13 15:15 UTC, danyaao commented on intensive/flutter-task-6/lib/data/themes_repository/themes_repository.dart
> +    try {
Я может проглядел, но вроде у тебя тут ошибка никогда не вернется

2024-05-13 15:15 UTC, danyaao commented on intensive/flutter-task-6/lib/presentation/widgets/themes_bottomsheet.dart
> +                as ThemeTextStyles;
Лучше тогда bang оператор в расширении, чем каст типа здесь

2024-05-14 09:16 UTC, khlebobul commented on intensive/flutter-task-6/lib/data/data_source/local_storage/local_storage_abstract.dart
> +  void set<T>(String key, T value);
Исправил

2024-05-14 09:21 UTC, khlebobul commented on intensive/flutter-task-6/lib/data/data_source/local_storage/themes_storage.dart
> +  final String _themeKey = 'Theme';
Сделал вот так, но понимаю, что лучше выносить в отдельный файл

2024-05-14 09:23 UTC, khlebobul commented on intensive/flutter-task-6/lib/presentation/widgets/themes_bottomsheet.dart
> +                as ThemeTextStyles;
Не совсем понял. Вот так?

2024-05-14 09:29 UTC, khlebobul commented on intensive/flutter-task-6/lib/data/themes_repository/themes_repository.dart
> +    return Future.value();
Я так и хотел, но выдается ошибка

>This expression has a type of 'void' so its value can't be used.
Try checking to see if you're using the correct API; there might be a function or call that returns void you didn't expect. Also check type parameters and variables which might also be void.

```dart
Future<void> saveTheme(String themeName) async {
  await themesStorage.setTheme(themeName);
}
```

IDE предлагает на такой код поменять

```dart
Future<void> saveTheme(String themeName) async {
  themesStorage.setTheme(themeName);
}
```

2024-05-14 09:30 UTC, khlebobul commented
Привет! Большое спасибо за проверку. Я исправил большинство моментов и оставил несколько уточняющих вопросов

2024-05-22 08:42 UTC, danyaao commented on intensive/flutter-task-6/lib/data/themes_repository/themes_repository.dart
> +    return Future.value();
Проблема в том, что у тебя метод themesStorage.setTheme не асинхронный. Хотя на самом деле, сохранение в SharedPreferences асинхронное. Я думаю, что правильно будет метод setTheme в ThemesStorage сделать асинхронным и в реализации дожидаться сохранения в SharedPreferences

2024-05-22 08:46 UTC, danyaao commented on intensive/flutter-task-6/lib/presentation/widgets/themes_bottomsheet.dart
> +                as ThemeTextStyles;
Просто меняешь
ThemeColors? get color => Theme.of(this).extension<ThemeColors>()
на
ThemeColors get color => Theme.of(this).extension<ThemeColors>()!
а дальше цвета получаешь через context.color

2024-05-22 09:01 UTC, danyaao approved these changes

2024-05-22 09:01 UTC, danyaao commented on intensive/flutter-task-6/lib/data/data_source/local_storage/shared_preferences_local_storage.dart
> +  Future set<T>(String key, T value) async {
Future<void>

2024-05-22 09:08 UTC, khlebobul commented on intensive/flutter-task-6/lib/data/themes_repository/themes_repository.dart
> +    return Future.value();
Спасибо, теперь стало понятнее

2024-05-22 09:08 UTC, danyaao commented
Ты решил всё-таки не передавать SharedPrefrences как параметр в интерактор?

2024-05-22 09:46 UTC, khlebobul commented on intensive/flutter-task-6/lib/data/data_source/local_storage/shared_preferences_local_storage.dart
> +  Future set<T>(String key, T value) async {
Я запутался с этим комментарием. Вот такая реализация должна быть: `Future<void> set<T>(String key, T value) async`?

2024-05-22 10:03 UTC, khlebobul commented
Спасибо, код переделал, SharedPrefrences решил не переделывать. Честно говоря, я не очень понял зачем.

2024-05-24 13:17 UTC, merged