complete photo_gallery task (intensive)
khlebobul/surf-flutter pull request #25
Opened 2024-05-25 12:23 UTC by khlebobul

2024-05-25 12:27 UTC, khlebobul commented
C загрузкой фото есть проблемы в том, как связять БД с хранилищем файлов. Тут проблема только том, что я пока не до конца разобрался в этом на стороне Supabase. Подскажите, как это можно сделать?
Дело в том, что URL загруженного изображения я могу получить только, если зайду в него и скопирую URL, в поле параметров URL нет.

(пока я самостоятельно решаю данную проблему)

2024-05-25 12:29 UTC, khlebobul commented
Uploading Screen Recording 2024-04-22 at 13.55.47.mov…

2024-05-25 12:31 UTC, khlebobul commented
https://github.com/khlebobul/surf-flutter/assets/77191581/78313408-b348-4cac-9f13-cc55dbf32020

2024-05-27 19:50 UTC, danyaao requested changes
Смотри, используя image_picker, ты не сможешь файл превратить в ссылку. Тебе нужно полностью переходить на картинки в формате Uint8List. Кажется, supabase поддерживает сохранение таких файлов. В ui будет соответственно Image.memory

2024-05-27 19:50 UTC, danyaao commented on intensive/flutter-task-7/lib/data/constants.dart
> +class PhotoCurrentIndexStyles {
Стили попали в data. Data - это слой данных, тут должна находиться самая бизнесовая логика, всякие репозитории, апи и т.п., стили в другое место, вроде uikit

2024-05-27 19:50 UTC, danyaao commented on intensive/flutter-task-7/lib/screens/home_screen.dart
> +const addPhotoIcon = Icon(Icons.add_a_photo_outlined);
А зачем оно вынесено?

2024-05-27 19:50 UTC, danyaao commented on intensive/flutter-task-7/lib/screens/home_screen.dart
> +const logoPath = 'assets/logo.png';
Мне кажется, лучше сделать файл с ассетами. Можешь поизучать библиотеку spider

2024-05-27 19:50 UTC, danyaao commented on intensive/flutter-task-7/lib/screens/home_screen.dart
> +                    }
Логику бы отсюда вынести

2024-05-27 19:50 UTC, danyaao commented on intensive/flutter-task-7/lib/screens/home_screen.dart
> +      body: PhotoGrid(),
const потерялся

2024-05-27 19:50 UTC, danyaao commented on intensive/flutter-task-7/lib/screens/photo_details.dart
> +  final List<String> imageUrls;
Немного неудачное название. Все-таки PhotoDetails это обычно какой-то виджет для одного конкретно фото. Лучше было бы что-то вроде PhotoPageView, а вот в itemBuilder'е этого PageView можно уже возвращать PhotoDetails

2024-05-27 19:50 UTC, danyaao commented on intensive/flutter-task-7/lib/screens/photo_details.dart
> +  _PhotoDetailState createState() => _PhotoDetailState();
@override
  State<MyWidget> createState() => _MyWidgetState();

2024-05-27 19:50 UTC, danyaao commented on intensive/flutter-task-7/lib/widgets/grid_gallery.dart
> +    for (var row in response) {
Можно final

2024-05-27 19:50 UTC, danyaao commented on intensive/flutter-task-7/lib/widgets/grid_gallery.dart
> +        await Utils.supabaseClient.from('photo').select('image_path');
Неплохо было бы вынести всю логику работы с бд из ui, а также можно добавить константы для ключиков

2024-05-28 05:38 UTC, khlebobul commented on intensive/flutter-task-7/lib/data/constants.dart
> +class PhotoCurrentIndexStyles {
Можно ли оставить тут файл для работы с API?

2024-05-28 05:40 UTC, khlebobul commented on intensive/flutter-task-7/lib/screens/home_screen.dart
> +      body: PhotoGrid(),
Точно, спасибо

2024-05-28 05:42 UTC, khlebobul commented on intensive/flutter-task-7/lib/screens/home_screen.dart
> +const logoPath = 'assets/logo.png';
Просто в моем случае в этом файле будет хранится только лого. Фотографии все равно загружаются из базы

2024-05-28 05:44 UTC, khlebobul commented on intensive/flutter-task-7/lib/screens/home_screen.dart
> +const addPhotoIcon = Icon(Icons.add_a_photo_outlined);
Подумал, что будет хорошо, если вынести в константу наверх или отдельный файл

2024-05-28 05:47 UTC, khlebobul commented on intensive/flutter-task-7/lib/screens/home_screen.dart
> +                    }
Сделал вот так 
```
 Future<void> _pickImage() async {
    final ImagePicker picker = ImagePicker();
    final XFile? image = await picker.pickImage(source: ImageSource.gallery);
    if (image == null) {
      return;
    }
    // Дальнейшая логика обработки выбранного изображения
  }
  ```

2024-05-28 05:47 UTC, khlebobul commented on intensive/flutter-task-7/lib/screens/home_screen.dart
> +                    }
Сделал вот так
```dart
  Future<void> _pickImage() async {
    final ImagePicker picker = ImagePicker();
    final XFile? image = await picker.pickImage(source: ImageSource.gallery);
    if (image == null) {
      return;
    }
  }
  ```

2024-05-28 05:52 UTC, khlebobul commented on intensive/flutter-task-7/lib/screens/photo_details.dart
> +  final List<String> imageUrls;
Согласен, поправил

2024-05-28 06:01 UTC, khlebobul commented on intensive/flutter-task-7/lib/widgets/grid_gallery.dart
> +        await Utils.supabaseClient.from('photo').select('image_path');
Я разделил на три файла: костанты, логика работы и ui. Можно ли файл с логикой работы поместить в data?

2024-05-28 06:05 UTC, khlebobul commented
Спасибо за проверку, насчет данного комментария понял 

> Смотри, используя image_picker, ты не сможешь файл превратить в ссылку. Тебе нужно полностью переходить на картинки в формате Uint8List. Кажется, supabase поддерживает сохранение таких файлов. В ui будет соответственно Image.memory

Я делал часть Supabase по [гайду](https://www.youtube.com/watch?v=SZ09mPSNu4k&list=PL5S4mPUpp4OtkMf5LNDLXdTcAp1niHjoL&index=5). Попытаюсь сегодня реализовать вечером

2024-05-30 20:28 UTC, danyaao requested changes

2024-05-30 20:28 UTC, danyaao commented on intensive/flutter-task-7/lib/data/photo_service.dart
> +        await Utils.supabaseClient.from(DbConstants.photoTable).select(DbConstants.imagePath);
Так, смотри, попробуй получать из Supabase не ссылки, а Uint8List, для SQL и по идее Supabase это будет тип Blob. Этот же тип ты сможешь insert'ить через ImagePicker. Я почти уверен, что есть такая возможность

2024-05-30 20:37 UTC, khlebobul commented on intensive/flutter-task-7/lib/data/photo_service.dart
> +        await Utils.supabaseClient.from(DbConstants.photoTable).select(DbConstants.imagePath);
Спасибо, я завтра и на выходных попробую сделать

2024-05-31 13:23 UTC, khlebobul commented on intensive/flutter-task-7/lib/data/photo_service.dart
> +        await Utils.supabaseClient.from(DbConstants.photoTable).select(DbConstants.imagePath);
Моя проблема просто еще связана с тем, что я не понимаю, как связать базу с хранилищем.

Это хранилище и тут нет доступа к URL изображения, поэтому не получается связать загруженные фото и базу с хранилищем
<img width="1123" alt="image" src="https://github.com/khlebobul/surf-flutter/assets/77191581/263dbaf8-454c-45c3-8254-bf95ec58cda4">

2024-06-09 19:22 UTC, khlebobul commented
Привет! Кажется, я победил, работает кривовато, но загружать фото могу теперь. Там уже работа с SQL, чтобы передавать ссылку с фото из хранилища а базу

https://github.com/khlebobul/surf-flutter/assets/77191581/61f5881c-cb35-4f27-b3bb-c1ac320b29f0

2024-06-17 10:50 UTC, danyaao approved these changes
Всё хорошо

2024-06-17 10:50 UTC, danyaao commented on intensive/flutter-task-7/lib/screens/home_screen.dart
> +savePhotoUrlToDatabase(String photoUrl) {}
Не забывай подчищать старый и ненужный код

2024-06-17 10:53 UTC, khlebobul commented on intensive/flutter-task-7/lib/screens/home_screen.dart
> +savePhotoUrlToDatabase(String photoUrl) {}
Спасибо

2024-06-17 11:56 UTC, merged