form validation task
khlebobul/surf-flutter pull request #27
Opened 2024-06-21 19:25 UTC by khlebobul

2024-06-23 12:54 UTC, khlebobul commented
![demo](https://github.com/khlebobul/surf-flutter/assets/77191581/8de84af2-ef23-4d55-a345-3d4b53d29c10)

2024-06-25 08:49 UTC, danyaao requested changes
Привет! Выглядит неплохо, но очень важно сделать валидацию на unfocus
И очень желательно через FormField сделать, материалы прикрепил выше. Тебе самому будет проще с этим поправить валидацию

2024-06-25 08:49 UTC, danyaao commented on flutter/flutter-task-9/lib/screen/home_screen.dart
> +  void _validateForm() {
А если, к примеру, увеличится количество полей для валидации? Будет больно расширять этот метод. Думаю, лучше сделать отдельный метод на каждое поле, а в этом методе их просто объединять

2024-06-25 08:49 UTC, danyaao commented on flutter/flutter-task-9/lib/screen/home_screen.dart
> +      }
Не хочешь попробовать через validator'ы?
Гайдик есть тут - https://docs.flutter.dev/cookbook/forms/validation
И вчера наш сеньор Сергей рассказывал эту тему, запись есть, тоже можно глянуть

2024-06-25 08:49 UTC, danyaao commented on flutter/flutter-task-9/lib/screen/home_screen.dart
> +          if (!_isLoading)
Лучше if else

2024-06-25 08:49 UTC, danyaao commented on flutter/flutter-task-9/lib/screen/home_screen.dart
> +                        }
В таких случаях можно просто предавать функцию, только без скобок
onPressed: _validateForm

2024-06-25 08:49 UTC, danyaao commented on flutter/flutter-task-9/lib/widgets/animal_button.dart
> +    super.key,
А ты не используешь линтер встроенный? Вроде должен ругаться здесь, что super параметр не в конце. Пока ты делаешь свои проекты, это не так важно, но в реальной работе уже нужно будет таких моментов избегать

2024-06-25 08:49 UTC, danyaao commented on flutter/flutter-task-9/lib/widgets/animal_check_box.dart
> +              rabies = value!;
Опасненько. Может лучше
?? false

2024-06-25 08:49 UTC, danyaao commented on flutter/flutter-task-9/lib/widgets/animal_check_box.dart
> +        if (covid)
Тут, к примеру, было бы не лишним немного декомпозировать. Можно вынести виджеты из if'ов, было бы гораздо приятнее читать код

2024-06-25 08:49 UTC, danyaao commented on flutter/flutter-task-9/lib/widgets/animals_form.dart
> +      },
Нужно валидировать поля после unfocus

2024-06-25 18:11 UTC, khlebobul commented on flutter/flutter-task-9/lib/widgets/animal_button.dart
> +    super.key,
Спасибо, честно говоря, никогда не было из-за этого ошибки, буду знать на будущее

2024-06-25 18:14 UTC, khlebobul commented on flutter/flutter-task-9/lib/widgets/animal_check_box.dart
> +        if (covid)
Согласен, спасибо

2024-06-25 18:16 UTC, khlebobul commented on flutter/flutter-task-9/lib/widgets/animals_form.dart
> +      },
Я изначально делал это для того, чтобы пользователь мог клавиатуру свернуть, но после вчерашней лекции понял, что можно и сразу проверять

2024-06-25 18:18 UTC, khlebobul commented on flutter/flutter-task-9/lib/screen/home_screen.dart
> +  void _validateForm() {
Да, согласен

2024-06-25 18:24 UTC, khlebobul commented on flutter/flutter-task-9/lib/screen/home_screen.dart
> +      }
Да, я вчера был на лекции. Можешь, пожалуйста, посмотреть коммит, который будет и предыдущий. Сначала залью без валидаторов, а потом с ними?

2024-06-27 09:28 UTC, danyaao approved these changes

2024-06-27 09:40 UTC, merged